### ISSUE TITLE
Optimizing for Columns instead of Rows?

### ISSUE THREAD

**Issue by graham768** [ToonVanEyck/OpenFlap#1]
Hey ToonVanEyck,

First of all, I love the work you've done. I think I stumbled onto this project fairly early considering the commit dates and the time stamps on your schematics, but you're really blowing the other "competition" out of the water by making these modules so compact and interchangeable.

With the interchangeability though, I was wondering why you optimized the design for columns. If I'm understanding correctly each column has to have its own top-con board, so if I made a board with 10 modules in a row I'd need 10 top-con boards? Whereas if I made a single column of 10 modules stacked tall, I'd only need a single top-con for the whole system? I would expect most users to have more modules in a row than a column as they write phrases. Let me know if I've misunderstood anything here!

**Comment by ToonVanEyck** [comment]
Hey Graham,

Thanks for your intrest in the project. 

Each module has two PCB side panels, only one of those PCB's (the left one) has any components on it. The other PCB is the just a structural part. When stacking the modules we can use the headers as implemented in the current design. If we would want to connect them left to right we would need to use a cable or other pcb to connect the left PCB of the first module with the left PCB of the next PCB. This seems like a more complex solution. 

Additionally, I wanted the display to be easy to disassemble in the field. It's important to be able to quickly replace one broken module from anywhere in the display. The the top and bottom of the side panel PCB's are rounded. (This is done to reduces the inter-line distance of the display.) Once the modules are stacked and placed in a display, it is impossible to remove a single module or an entire row from a display. It's only possible to remove an entire column from the display, and then break apart that column to replace a broken module. 

Because we already have all the connections available on the topmost modules of each column it seemed logical to add a board to facilitate wiring them together.

NOTE: It's entirely possible to wire multiple modules in a row without the use of the top-con boards. (An external 5V supply is required.) The top-con just simplify this greatly.

I agree that horizontal stacking would be more favourable for most users. But the vertical stacking and interconnection was just more practical to implement.  The top-con board allows the horizontal connections to be made with a simple flat-cable to simplify the wiring.
