### ISSUE TITLE
[DISCUSSION] Support for multi-width & multi-format displays

### ISSUE THREAD

**Issue by sashahilton00** [ToonVanEyck/OpenFlap#5]
Hi,

I was wondering if there are any plans to support larger displays, both in terms of number of modules, but also in terms of modules of differing width, such as:

![image](https://github.com/ToonVanEyck/OpenFlap/assets/4185362/2913e033-697e-4b55-8275-368563939706)

I have a few thoughts on how one might do this, and might prototype a little, but wanted to check if there is already a WIP on this front:

- Looking at the designs, I'm slightly concerned that if one connected a couple of hundred modules together, that there may be concerns around power draw, possibly necessitating a seperate header (unpopulated by default) for power on each module, which could be used instead of the power from the 16 pin connector for powering the PIC/motor.
- For the multi width side of things, the simplest way in my mind, is to say that the standard module is 1 unit wide, then allow for multiples of the standard unit to be used, to keep the grid type web UI simple, and retain the neat auto discovery functionality.
- Each unit would then store it's size (eg. unit width: 3) in the MCU, and to allow the columnar communication system to continue to work, one would have a simple bridging board that linked the modules above and below an extended width module, with a stored unit length of zero. In this way, a module that detected a module connected below it (ie. column end = false), where that module had a unit width of 0, would allow it to determine that it was sitting on top of a module with a unit length > 1, and be displayed accordingly in the UI. This would probably also require a minor modification to add a lip to the top and bottom casing that would allow modules to snap into to retain their position.

**Comment by ToonVanEyck** [comment]
Hi, 

Interesting! 

I currently do not plan on developing wider modules. I think you are on the right track. E.g.: A 3 wide module should contain 1 PCB with microcontroller, motor, etc... Configured with a `module_width = 3`. And 2 PCBs which just pass through the data signals. These 2 passthrough PCBs should also detect if they are at the end of a column and reroute the data accordingly. I don't think they would require a `module_width = 0`, they don't require a microcontroller. The OpenFlap Controller should be able to calculate the date order in order to "skip" the passthrough PCBs.

Regarding the power usage: 
I don't know the power draw at the moment, but the column height will be the limiting factor here. For multiple rows it's trivial to create a customized cable that powers different columns from different supplies. I have ordered materials to build 30 modules, this will allow me to profile the power usage of a somewhat larger display. 

I also had the idea for different kinds of modules, e.g.: 7-segment, 16-segment, dotmatrix, nixie tube,... 

Regards,
Toon

**Comment by sashahilton00** [comment]
I hadn't even thought about the possibility of different types of displays, but that would be very neat. The `module_width = 0` concept was more to account for the fact that columns may not be right next to each other, but spaced out, eg:

![image](https://github.com/ToonVanEyck/OpenFlap/assets/4185362/5d94cf22-0b7b-4e48-9c79-d53e0d98f5ff)

i.e. the software may think that a module with `module_width = 1` is above/below a module with `module_width = 3`, where in fact it is off to the side, after the 3 width module. However, looking at layouts such as the one above, I'm not sure this is an issue worth facing right now, as I have yet to find many module layouts where the widths of the modules are mixed for a single column. For any edge cases, it's probably easier + cheaper to handle this in the controller as you mention.

It's been a little while since I've played around in autocad/eagle, but will try to pick it back up and make some proof of concepts for wider modules/bridging boards.

In the meantime, I'll rename this issue as a discussion thread for multi width/format displays and leave it open for future discussion/thoughts.
